services:
    - name: runtime
      build:
        context: .
      env:
        - name: NB_UID
          value: codeany
      volumeMounts: []
      limits:
        cpu: 2
        memory: 8
    - name: pgadmin
      image: dpage/pgadmin4
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@email.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: pass
        - name: PGADMIN_LISTEN_PORT
          value: 55400
      volumeMounts: []
      limits:
        cpu: 2
        memory: 8
    - name: db
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: pass
      volumeMounts: []
      limits:
        cpu: 2
        memory: 8
volumes: []
tasks:
  - name: jupyter_config_copy
    command: sleep 3s && mkdir -p /home/codeany/.jupyter && cp /app/jupyter_notebook_config.py /home/codeany/.jupyter/jupyter_notebook_config.py
    serviceName: runtime
    type: exec
