services:
    - name: runtime
      build:
        context: .
      env:
        - name: NB_UID
          value: codeany
      volumeMounts: []
      limits:
        cpu: 2
        memory: 8
volumes: []
tasks:
  - name: jupyter_config_copy
    command: sleep 3s && cp /app/jupyter_notebook_config.py /home/codeany/.jupyter/jupyter_notebook_config.py
    serviceName: runtime
    type: exec
