services:
    - name: runtime
      build:
        context: .
      env:
        - name: NB_UID
          value: codeany
      volumeMounts: []
      limits:
        cpu: 1
        memory: 8
volumes: []
tasks: []
